### ISSUE TITLE
Throw custom Exception

### ISSUE THREAD

**Issue by kobelobster** [alexschwarz89/easy-mysqli-fulltext#3]
You throw a default Exception, which makes it hard for web applications to handle those in a good way. Is it possible that you throw a custom exception, so it's easier for me/us to catch those? Thanks.

**Comment by alexschwarz89** [comment]
Thanks. Fixed in commit 9648c744d398d7e747c63a4f886287bc50cb3791

**Comment by kobelobster** [comment]
That was fast, thanks!
